server:
  port: 9520
spring:
  rabbitmq:
    host: localhsot
    port: 5672
    username: test
    password: test
    virtual-host: /test
    ##消息发送到交换机确认机制,是否确认回调
    publisher-confirms: true
    ##消息发送到交换机确认机制,是否返回回馈
    publisher-returns: true
