server:
  port: 9521
spring:
  rabbitmq:
    host: localhsot
    port: 5672
    username: test
    password: test
    virtual-host: /test
    ##消息发送到交换机确认机制,是否确认回调
    publisher-confirms: true
    ##配置该消费者的ack方式为手动
    listener:
      direct:
        acknowledge-mode: manual
  devtools:
    restart:
      enabled: false
